;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Damage.Affinity.Poison",DevComment="")
+GameplayTagList=(Tag="Damage.Mechanic.DoT",DevComment="")
+GameplayTagList=(Tag="Damage.Mechanic.Execution",DevComment="")
+GameplayTagList=(Tag="Damage.Mechanic.InstantKill",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Poison",DevComment="")

